<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_komentar_model extends CI_Model
{

    public $table = 'tbl_komentar';
    public $id = 'id_komen';
    public $id_berita = 'id_berita';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_id_berita($id_berita)
    {
        $this->db->where($this->id_berita, $id_berita);
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_komen', $q);
	$this->db->or_like('id_parent_komen', $q);
	$this->db->or_like('id_berita', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('komen', $q);
	$this->db->or_like('captcha', $q);
	$this->db->or_like('tgl_input', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_komen', $q);
	$this->db->or_like('id_parent_komen', $q);
	$this->db->or_like('id_berita', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('komen', $q);
	$this->db->or_like('captcha', $q);
	$this->db->or_like('tgl_input', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_komentar_model.php */
/* Location: ./application/models/Tbl_komentar_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-09 05:56:29 */
/* http://harviacode.com */