<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_balas_komentar_model extends CI_Model
{

    public $table = 'tbl_balas_komentar';
    public $id = 'id_balas';
    public $id_komen = 'id_komen';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    // get data by idkomen
    function get_by_id_komen($id_komen)
    {
        $this->db->where($this->id_komen, $id_komen);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_balas', $q);
	$this->db->or_like('id_komen', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('komen', $q);
	$this->db->or_like('captcha', $q);
	$this->db->or_like('tgl_input', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_balas', $q);
	$this->db->or_like('id_komen', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('komen', $q);
	$this->db->or_like('captcha', $q);
	$this->db->or_like('tgl_input', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_balas_komentar_model.php */
/* Location: ./application/models/Tbl_balas_komentar_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-08 11:42:41 */
/* http://harviacode.com */